### ISSUE TITLE
Kvalue of 1 may not be working as intended

### ISSUE THREAD

**Issue by user404d** [DougSteiert/ResearchApp#6]
This [commit](https://github.com/DougSteiert/ResearchApp/commit/2cabe18663bcec78b7ac3edef943437e2e237bc9) fixed a major bug where the application would fail to work correctly with a kvalue of 1. The application would crash because cityCoords will have a size of zero after the randLocs generated by GenerateNearbyCities. This behavior is still present, but has a *temporary* fix. The issue can be found [here](https://github.com/DougSteiert/ResearchApp/blob/master/LocationPrivacyApp/app/src/main/java/com/djsg38/locationprivacyapp/GenerateNearbyCities.java#L53).

**Comment by DougSteiert** [comment]
Fixed. This was different than what I had written in the paper, anyway.
